### ISSUE TITLE
Error when running h5p create-language-file

### ISSUE THREAD

**Issue by juho-jaakkola** [h5p/h5p-cli#12]
I have:
 1. Set up a Drupal instance
 2. Enabled the `Enable library development directory` setting
 3. Installed `h5p-course-presentation` to `development/` directory
 4. Installed the cli tool with `npm -g install h5p`

I go to the directory :
```
/var/www/drupal/h5p/sites/default/files/h5p/development/h5p-course-presentation/
```
I try to create language file with:
```
h5p create-language-file h5p-course-presentation fi
```
But I get the error:
```
fs.js:436
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'h5p-course-presentation/language/fi.json'
    at Object.fs.openSync (fs.js:436:18)
    at Object.fs.writeFileSync (fs.js:975:15)
    at /usr/local/lib/node_modules/h5p/lib/h5p.js:1158:8
    at readSemantics (/usr/local/lib/node_modules/h5p/lib/h5p.js:734:5)
    at Object.h5p.createLanguageFile (/usr/local/lib/node_modules/h5p/lib/h5p.js:1156:3)
    at Object.commands.handler (/usr/local/lib/node_modules/h5p/bin/h5p-cli.js:556:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/h5p/bin/h5p-cli.js:764:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```
Any idea what might be causing this?

**Comment by juho-jaakkola** [comment]
It seems I hadn't installed `h5p-course-presentation` properly. The command started working once I ran:
```
h5p get h5p-course-presentation
```
